# These set of workflows run on every push to the main branch
name: PR Checks

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck
    uses: ./.github/workflows/spellcheck.yml
  linting:
    name: Linting
    uses: ./.github/workflows/lint.yml
  security-scan:
    name: Security Scan
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/security-scan.yml
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
  docs:
    name: Docs
    uses: ./.github/workflows/verify-docgen.yml
  codegen:
    name: Codegen
    uses: ./.github/workflows/verify-gen.yml