# These set of workflows run on every push to the main branch
name: Main build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/lint.yml
  security-scan:
    name: Security Scan
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/security-scan.yml
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
  codegen:
    name: Codegen
    uses: ./.github/workflows/verify-gen.yml
  image-build-and-push:
    name: Build and Sign Image
    needs: [ linting, security-scan, tests, codegen ]
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/image-build-and-publish.yml